AvinashSingh88/ebb_admin

- app/Http/Controllers/CatController.php
- app/Http/Controllers/HomeController.php
- app/Http/Controllers/SearchController.php
- app/Models/Enquiry.php
- public/assets_web/css/style.css
- public/assets_web/js/custom.js
- public/assets_web/js/slider.js
- resources/views/frontend/header.blade.php
- resources/views/frontend/index.blade.php
- resources/views/frontend/master.blade.php
- resources/views/frontend/old/product_listing.blade.php
- resources/views/frontend/product_details.blade.php
- resources/views/frontend/product_listing.blade.php
- resources/views/frontend/sub_category.blade.php
- resources/views/frontend/view_cart.blade.php
- routes/web.php
> Rana sharma

- app/Http/Controllers/CatController.php
- app/Http/Controllers/CategoryController.php
- public/assets_web/css/style.css
- resources/views/backend/product/categories/create.blade.php
- resources/views/backend/product/categories/edit.blade.php
- resources/views/frontend/partials/product_box_1.blade.php
- resources/views/frontend/product_details.blade.php
- resources/views/frontend/product_listing.blade.php
- resources/views/frontend/sub_category.blade.php
> Category Update from Admin Panel

- resources/views/frontend/index.blade.php
- resources/views/frontend/partials/home_categories_section.blade - Copy.php
- resources/views/frontend/partials/home_categories_section.blade.php
> Ranasecond

- app/Http/Controllers/CartController.php
- resources/views/frontend/master.blade.php
- resources/views/frontend/partials/product_box_1.blade.php
- resources/views/frontend/product_listing.blade.php
product list add to cart added
> product list add to cart added

- resources/views/frontend/header.blade.php
> header menu updated

- app/Http/Controllers/CartController.php
- app/Http/Controllers/HomeController.php
- app/Http/Controllers/OrderController.php
- app/Models/CallRequest.php
- app/Models/Order.php
- app/Models/OrderDetail.php
- public/assets_web/js/custom.js
- resources/views/frontend/footer.blade.php
- resources/views/frontend/header.blade.php
- resources/views/frontend/master.blade.php
- resources/views/frontend/partials/cart_details.blade.php
- resources/views/frontend/partials/cart_update_ajax.blade.php
- resources/views/frontend/sub_category.blade.php
- resources/views/frontend/user/purchase_history.blade.php
- resources/views/frontend/view_cart.blade.php
- routes/web.php
Cart page update and remove issue fixed
> Cart page update and remove issue fixed

- resources/views/frontend/master.blade.php
- resources/views/frontend/product_listing.blade.php
Price range Fixed in product listing page
> Price range Fixed in product listing page

- public/assets_web/css/style.css
- public/assets_web/js/slider.js
- resources/views/frontend/footer.blade.php
- resources/views/frontend/header.blade.php
- resources/views/frontend/index.blade.php
- resources/views/frontend/master.blade.php
- resources/views/frontend/partials/cart.blade.php
> Header issue solve

- app/Http/Controllers/ServiceController.php
- app/Models/Service.php
- app/Models/ServiceStock.php
- app/Models/ServiceTax.php
- app/Models/ServiceTranslation.php
- resources/views/backend/inc/admin_sidenav.blade.php
- resources/views/backend/services/create.blade.php
- resources/views/backend/services/edit.blade.php
- resources/views/backend/services/index.blade.php
- resources/views/backend/services/sku_combinations.blade.php
- resources/views/backend/services/sku_combinations_edit.blade.php
- resources/views/errors/404.blade.php
- routes/admin.php
- routes/web.php
> services crud

- public/assets_web/css/style.css
- resources/views/frontend/header.blade.php
update header blade and style.css
> update header blade and style.css

- public/assets_web/css/style.css
- resources/views/frontend/header.blade.php
- resources/views/frontend/product_listing.blade.php
third level products, header changes
> third level products, header changes

- public/assets_web/css/style.css
- resources/views/frontend/master.blade.php
- resources/views/frontend/product_listing.blade.php
drop down, product third category, product thumb image fix
> drop down, product third category, product thumb image fix

- resources/views/frontend/index.blade.php
- resources/views/frontend/partials/category_enquiry_form.blade.php
product, services and list message form
> product, services and list message form

- resources/views/frontend/product_listing.blade.php
> product list page updated

- public/assets_web/css/style.css
- resources/views/frontend/header.blade.php
- resources/views/frontend/partials/cart.blade.php
- resources/views/frontend/user/edit_profile.blade.php
- resources/views/frontend/user/my-addressbook.blade.php
- resources/views/frontend/user_login.blade.php
> Profile Design update

- public/assets_web/css/style.css
- resources/views/frontend/inc/user_side_nav.blade.php
- resources/views/frontend/partials/cart.blade.php
- resources/views/frontend/partials/product_box_1.blade.php
- resources/views/frontend/product_details.blade.php
- resources/views/frontend/product_listing.blade.php
- resources/views/frontend/user_login.blade.php
product listing page and css fixing
> product listing page and css fixing

- customer_product_listing.blade.php
- resources/views/frontend/index.blade.php
- resources/views/frontend/user/edit_profile.blade.php
- resources/views/frontend/user/profile.blade.php
- resources/views/frontend/user_login.blade.php
> update user section

- public/assets_web/css/style.css
- resources/views/frontend/user/edit_profile.blade.php
- resources/views/frontend/user_login.blade.php
update login, edit profile and truncate home page text
> update login, edit profile and truncate home page text

- public/assets_web/css/style.css
- resources/views/frontend/product_details.blade.php
- resources/views/frontend/user/manage-payments.blade.php
> update seller popup

- app/Http/Controllers/HomeController.php
- resources/views/frontend/more_seller.blade.php
- resources/views/frontend/product_details.blade.php
- routes/web.php
> please update seller pages

- resources/views/frontend/flash_deal_details.blade.php
> flash deal details updated

- public/assets_web/css/bootstrap.mins.css
- public/assets_web/css/style.css
- resources/views/frontend/partials/product_box_1.blade.php
- resources/views/frontend/product_listing.blade.php
> update product listing pages

- public/assets_web/css/style.css
- public/assets_web/js/custom.js
- resources/views/frontend/more_seller.blade.php
- resources/views/frontend/product_details.blade.php
> update product detail pages

- public/assets_web/css/style.css
- public/assets_web/js/slider.js
- resources/views/frontend/more_seller.blade.php
> seller page changes

- public/assets_web/css/nouislider.css
- public/assets_web/css/style.css
- resources/views/frontend/partials/product_box_1.blade.php
- resources/views/frontend/product_listing.blade.php
> Product listing update

- public/assets_web/css/style.css
- public/assets_web/js/slider.js
- resources/views/frontend/more_seller.blade.php
> please update more seller

- public/assets_web/css/style.css
- public/assets_web/js/slider.js
- resources/views/frontend/header.blade.php
- resources/views/frontend/more_seller.blade.php
> more seller update

- app/Http/Controllers/ProductController.php
- resources/views/backend/marketing/flash_deals/create.blade.php
- resources/views/backend/product/products/bought_together_edit.blade.php
- resources/views/backend/product/products/bought_togethers.blade.php
- resources/views/backend/product/products/create.blade.php
- resources/views/backend/product/products/edit.blade.php
- resources/views/backend/product/products/related_products.blade.php
- resources/views/backend/product/products/related_products_edit.blade.php
- routes/admin.php
bought tog& Rel pro added in admin CR
> bought tog& Rel pro added in admin CR

- public/assets_web/css/style.css
- public/assets_web/js/slider.js
- resources/views/frontend/header.blade.php
> mega menu updates

- public/assets_web/css/style.css
- public/assets_web/js/slider.js
- resources/views/frontend/header.blade.php
> update mega menu

- bootstrap/cache/.gitignore
- resources/views/backend/sellers/index.blade.php
> add new seller

- app/Http/Controllers/HomeController.php
- resources/views/frontend/master.blade.php
- resources/views/frontend/more_seller.blade.php
- resources/views/frontend/product_details.blade.php
- routes/web.php
> more seller

- public/assets_web/css/bootstrap.mins.css
- public/assets_web/css/style.css
- resources/views/frontend/header.blade.php
- resources/views/frontend/partials/bought_together.blade.php
- resources/views/frontend/partials/category_enquiry_form.blade.php
- resources/views/frontend/product_details.blade.php
- resources/views/frontend/product_listing.blade.php
> please update changes

- public/assets_web/css/style.css
- public/assets_web/js/slider.js
- resources/views/frontend/more_seller.blade.php
- resources/views/frontend/product_details.blade.php
Please update more seller and product detail
> Please update more seller and product detail
